<?php
/**
 * Copyright © 2016 ShopGo. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @see \ShopGo\SkyNet\Block\Adminhtml\System\Config\Account\Verify
 */
?>
<script>
require([
    'jquery',
    'Magento_Ui/js/modal/alert'
], function(jQuery, alert) {

//<![CDATA[
    var configFieldIdPrefix = '#carriers_skynet_';
    var isModifiedUsername = 0;
    var isModifiedPassword = 0;
    var defaultMessage = '<?php echo __(
        'The triggered action status is unknown!'
        . ' If the issue persists, please contact the module author.'
    ) ?>';

    function verifyAccount() {
        var params = {
            username: jQuery(configFieldIdPrefix + 'username').val(),
            password: jQuery(configFieldIdPrefix + 'password').val(),
            station_code: jQuery(configFieldIdPrefix + 'station_code').val(),
            consignor_account: jQuery(configFieldIdPrefix + 'consignor_account').val(),
            is_modified_username: isModifiedUsername,
            is_modified_password: isModifiedPassword,
            form_key: FORM_KEY
        };

        jQuery.ajax({
            url: '<?php /* @escapeNotVerified */ echo $block->getAjaxUrl() ?>',
            method: 'POST',
            data: params,
            dataType: 'json',
            showLoader: true,
            success: function(response) {
                var result = defaultMessage;

                if (response.status || response.status === 0) {
                    result = response.description;
                }

                alert({
                    content: result
                });
            },
            error: function(response) {
                alert({
                    content: defaultMessage
                });
            }
        });
    }

    jQuery(configFieldIdPrefix + 'username').on('change', function(e) {
        isModifiedUsername = 1;
    });
    jQuery(configFieldIdPrefix + 'password').on('change', function(e) {
        isModifiedPassword = 1;
    });

    window.verifyAccount = verifyAccount;
//]]>

});
</script>
<div class="actions actions-verify-account">
    <button onclick="javascript:verifyAccount(); return false;" class="action-verify-account" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
